---
image: node:alpine

# silly BitBucket does NOT support global variables in pipelines YML.

options:
    max-time: 120
    docker: true
    size: 2x

definitions:
    services:
        docker:
            memory: 4096

#
# Pipeline definitions
#
pipelines:
    default:
        - step:
              name: Snapshot - eslint, test & dependency checks
              trigger: automatic
              caches:
                  - node
              script:
                  - export CI=true
                  - npm install -g npm@latest
                  - npm install
                  - npm run build
                  - npm run test
