---
name: CI/CD Pipeline

"on":
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  default-steps:
    name: Install, Build, Lint, Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          npm install

      - name: Run linting and tests
        run: |
          npm run build
          npm run test
